### ISSUE TITLE
Bugs for certain users that use a specific layout

### ISSUE THREAD

**Issue by Sammers21** [Sammers21/sArena_Updated2_by_sammers#13]
Some of the users having issues like that:
![image](https://github.com/user-attachments/assets/334cd540-2b2a-4118-a7d3-2283dbca3e58)

when /sarena is being type the issue appers:
![image](https://github.com/user-attachments/assets/28bbcf75-7499-4eb2-81b2-15cc39e9f047)

Here is some of the errors from bugrubber:
```
19x ...a_Updated2_by_sammers/Modules/DiminishingReturns.lua:88: attempt to index local 'layoutdb' (a nil value)
[string "@sArena_Updated2_by_sammers/Modules/DiminishingReturns.lua"]:88: in function `UpdateDRPositions'
[string "*sArena.xml:50_OnShow"]:1: in function <[string "*sArena.xml:50_OnShow"]:1>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCooldown'
[string "@sArena_Updated2_by_sammers/Modules/DiminishingReturns.lua"]:68: in function `FindDR'
[string "@sArena_Updated2_by_sammers/sArena.lua"]:137: in function <sArena_Updated2_by_sammers/sArena.lua:113>

Locals:
self = sArenaEnemyFrame2 {
 SpecIcon = Frame {
 }
 healAbsorbBarRightShadow = Texture {
 }
 PowerText = FontString {
 }
 Incapacitate = Frame {
 }
 healthbar = StatusBar {
 }
 TexturePool = <table> {
 }
 ClassIconMask = MaskTexture {
 }
 myHealPredictionBar = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 healAbsorbBar = Texture {
 }
 unit = "arena2"
 CastBar = StatusBar {
 }
 totalAbsorbBar = Texture {
 }
 currentClassIconTexture = "class"
 Trinket = Frame {
 }
 Name = FontString {
 }
 otherHealPredictionBar = Texture {
 }
 parent = sArena {
 }
 currentClassIconStartTime = 0
 healAbsorbBarLeftShadow = Texture {
 }
 Stun = Frame {
 }
 totalAbsorbBarOverlay = Texture {
 }
 overAbsorbGlow = Texture {
 }
 ClassIconCooldown = Cooldown {
 }
 specTexture = 135846
 Racial = Frame {
 }
 currentAuraDuration = 0
 Disorient = Frame {
 }
 race = "NightElf"
 PowerBar = StatusBar {
 }
 class = "MAGE"
 HealthBar = StatusBar {
 }
 Root = Frame {
 }
 currentAuraStartTime = 0
 DeathIcon = Texture {
 }
 Silence = Frame {
 }
 hideStatusText = false
 HealthText = FontString {
 }
 ClassIcon = Texture {
 }
}
layoutdb = nil
numActive = 0
frame = nil
prevFrame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'layoutdb' (a nil value)"
drCategories = <table> {
 1 = "Stun"
 2 = "Incapacitate"
 3 = "Disorient"
 4 = "Silence"
 5 = "Root"
}
```

```
578x FontString:SetText(): Font not set
Lua Taint: sArena_Updated2_by_sammers
[string "=[C]"]: in function SetText'
[string "@sArena_Updated2_by_sammers/sArena.lua"]:959: in function SetStatusText'
[string "@sArena_Updated2_by_sammers/sArena.lua"]:516: in function SetMysteryPlayer'
[string "@sArena_Updated2_by_sammers/sArena.lua"]:466: in function UpdatePlayer'
[string "@sArena_Updated2_by_sammers/sArena.lua"]:340: in function <sArena_Updated2_by_sammers/sArena.lua:327>

Locals:
(temporary) = FontString {
}
(temporary) = ""
```

**Comment by devai42coding** [comment]
@Sammers21 Can you verify with the user that he is running the latest sarena version? The background on the frames being invisible and the variable healAbsorbBarRightShadow showing in the bugsack could indicate this is an earlier version than the newest.

**Comment by Sammers21** [comment]
Yes @devai42coding i checked his version in curseforge it was the latest one on the curseforge:
https://github.com/Sammers21/sArena_Updated2_by_sammers/releases/tag/2024.7.2-pre.559e830

And i think there is other ppl who has updated and have some issue.

**Comment by Sammers21** [comment]
In curse forge it was showing as the version is the latest, i guess its not. That's weird. I aslo have noticed that test is looking a little weird: 
![image](https://github.com/user-attachments/assets/f0c9cf8c-17b9-4b15-b399-ad0b14b2963e)
![image](https://github.com/user-attachments/assets/89f51575-b6bc-41dd-a589-015c8567fe41)

**Comment by devai42coding** [comment]
@Sammers21 Yes switching layout will cause this and requires a /reload - Not sure what is causing it, so maybe to avoid it a reload should be forced somehow when switching layouts. Havent spent too much time on it because it’s a one time thing for most people. They select their layout and they are set.

Also not sure if you saw my previous question:
Also a side question. What addon do you make the graphics so much high resolution on partyframes, icons, sarena like the screenshots above? Looks clean.

**Comment by Sammers21** [comment]
> Also a side question. What addon do you make the graphics so much high resolution on partyframes, icons, sarena like the screenshots above? Looks clean.

I don't use anything specific. The reason it looks like that is proly because i use a 4k screen.

**Comment by devai42coding** [comment]
@Sammers21 Ah alright, that makes sense. Then I just don’t understand why the absorb colors looks different for you than me (I posted some screenshots in the merged PR)

**Comment by devai42coding** [comment]
> In curse forge it was showing as the version is the latest, i guess its not. That's weird. I aslo have noticed that test is looking a little weird: ![image](https://private-user-images.githubusercontent.com/16746106/352693244-f0c9cf8c-17b9-4b15-b399-ad0b14b2963e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjc2MTgsIm5iZiI6MTcyMjE2NzMxOCwicGF0aCI6Ii8xNjc0NjEwNi8zNTI2OTMyNDQtZjBjOWNmOGMtMTdiOS00YjE1LWIzOTktYWQwYjE0YjI5NjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZTFiYTJlMzE4YzExMWY3MzE3M2JjYjZmY2VkZGQ5Mjc0YWM4MjhmMWEwYzI0OTIxYWQzMTI1OWUzYTM1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vDi0oswJpKi_cJyKmj0G13WqtV0WxDTHXhLJ5SGuLoA) ![image](https://private-user-images.githubusercontent.com/16746106/352693281-89f51575-b6bc-41dd-a589-015c8567fe41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjc2MTgsIm5iZiI6MTcyMjE2NzMxOCwicGF0aCI6Ii8xNjc0NjEwNi8zNTI2OTMyODEtODlmNTE1NzUtYjZiYy00MWRkLWE1ODktMDE1Yzg1NjdmZTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExNDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MTk1ZDMxMmJkOTcxYTc2MTE5MzUyNmMzZDlhNDllNzgzZDBlMTc1MGQwNDk4ODJhZWI2ZmQwNTI3ZDNiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0sFgi4F-7mU-8n-3MEze3JBlAPEJiDWajoIRXzUUgY)

To avoid confusion regarding the textures, I have added this:
![image](https://github.com/user-attachments/assets/c6709d9a-0da3-4538-b216-3512bf3e12f7)

When switching layout in sArena, it will prompt the user and ask to reload.

PR:
https://github.com/Sammers21/sArena_Updated2_by_sammers/pull/14

**Comment by Sammers21** [comment]
@devai42coding, cool.

Look at this btw: https://www.twitch.tv/videos/2209579357?t=01h40m24s

sArena looks dark on his steram, the colors:
![image](https://github.com/user-attachments/assets/0815de29-bf39-41ec-b9aa-634c94b51f46)

**Comment by Sammers21** [comment]
![image](https://github.com/user-attachments/assets/4cde3d59-1cc4-4830-867a-933ad336ae76)
everything is looking very dark

**Comment by devai42coding** [comment]
> @devai42coding, cool.
> 
> Look at this btw: https://www.twitch.tv/videos/2209579357?t=01h40m24s
> 
> sArena looks dark on his steram, the colors: ![image](https://private-user-images.githubusercontent.com/16746106/352853002-0815de29-bf39-41ec-b9aa-634c94b51f46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODU0ODksIm5iZiI6MTcyMjE4NTE4OSwicGF0aCI6Ii8xNjc0NjEwNi8zNTI4NTMwMDItMDgxNWRlMjktYmYzOS00MWVjLWI5YWEtNjM0Yzk0YjUxZjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDE2NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZTBhYTllNWM2MjIxZWExYzljN2U4ZmMyZjQ4NjgzNDdlOGUzNjg1Y2UyNjI0YWI0YjMyMTBjMjk4NDYwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHVdhyPcg03UG3tqAk8F-ctr4McyeVc-lmnOl6HhIUc)

My guess is it’s an addon interferring since I have never seen that nor have I seen it on other streams I have watched.

**Comment by Sammers21** [comment]
Not sure, but could be ye.

**Comment by Sammers21** [comment]
@devai42coding can you look at this please: 
<img width="299" alt="image" src="https://github.com/user-attachments/assets/ced82941-fd7c-4f09-bf11-3febe1a54fc2">

Thats from Lontars strem: https://www.twitch.tv/videos/2210263573?t=02h18m43s

**Comment by devai42coding** [comment]
> @devai42coding can you look at this please: <img alt="image" width="299" src="https://private-user-images.githubusercontent.com/16746106/353001939-ced82941-fd7c-4f09-bf11-3febe1a54fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzE3NTQsIm5iZiI6MTcyMjI3MTQ1NCwicGF0aCI6Ii8xNjc0NjEwNi8zNTMwMDE5MzktY2VkODI5NDEtZmQ3Yy00ZjA5LWJmMTEtM2ZlYmUxYTU0ZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2M2NGMxYTI4MmE5MWQxOTEyMjVjYjI3ZWRhNjk5M2ZhYWZiMTA4OTBlYjJkN2I5OTgzODk3N2RjMDE5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9cl3hzVNvVix9LKQ7nBeH7wg8OLRE9b3Gk4yWyzhhQA">
> 
> Thats from Lontars strem: https://www.twitch.tv/videos/2210263573?t=02h18m43s

I see the issue, try this:
https://github.com/Sammers21/sArena_Updated2_by_sammers/pull/15

**Comment by Sammers21** [comment]
@devai42coding thanks, that fixed that issue and the one with shadowing
