### ISSUE TITLE
Feature request: New layout

### ISSUE THREAD

**Issue by wiltedwill** [Sammers21/sArena_Updated2_by_sammers#17]
Would it be possible to add a new layout that uses the modern WoW target frames/cast bars?

**Comment by Sammers21** [comment]
@wiltedwill i'm not sure what exactly you mean. Can you show some screenshots of that?

**Comment by wiltedwill** [comment]
The current "Blizz Target" layout uses the old textures for target frames. The current target frames and cast bars in retail WoW have been updated. I exported the WoW art and code an found the updated textures in `BlizzardInterfaceArt\Interface\HUD\UIUnitFrame.BLP` and a template for target frames in `BlizzardInterfaceCode\Interface\AddOns\Blizzard_UnitFrame\TargetFrame.xml` called `TargetFrameTemplate`. My request is to add a "Blizz Target (Modern)" layout that uses the updated textures for target frames and cast bars. 

![image](https://github.com/user-attachments/assets/604b991a-c385-42d1-a0e5-1b6bdac9af25)
> *Old Target Frames* (Blizz Target Layout)

![image](https://github.com/user-attachments/assets/e5287b40-f81a-4a78-84c2-79495f9276d8)
> *New Target Frames/Cast-Bars*

**Comment by Ma1ithorne** [comment]
Hey, I've gotten to this point utilizing in-game assets, if you'd be interested in using it as a base or outright adding it as a layout? I'm not well-versed in Lua so it's all very experimental, but I'll likely keep trying to refine it.

[BlizzModern.txt](https://github.com/user-attachments/files/17333869/BlizzModern.txt)

![image](https://github.com/user-attachments/assets/22c779f2-65ff-417c-b442-284be9f28435)

**Comment by Sammers21** [comment]
@Ma1ithorne sure, can add that as a separated layout. Send it in a Pull request. I will have a look

**Comment by Sammers21** [comment]
fix in #19
