### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Squimbert** [Sammers21/sArena_Updated2_by_sammers#6]
Hey! Would you please be able to allow us to choose a specific icon for each DR?  Like always show mighty bash as stun DR for example.  Thank you for maintaining this!

**Comment by Sammers21** [comment]
@Squimbert thank you for the feature request. But my main goal is to keep sArena functioning properly. I dont have a goal to develop new features. But who knows... maybe one day

**Comment by devai42coding** [comment]
I kinda like this idea - I have made a PR for TWW beta that adds this option in case it is wanted:
https://github.com/Sammers21/sArena_Updated2_by_sammers/pull/7

**Comment by Squimbert** [comment]
that looks awesome! i hope sammers will add it
